name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
    - name: make
      run: make

    - name: Checkout Project
      uses: actions/checkout@v4.2.2
    - name: Build Project
      uses: threeal/cmake-action@v2.0.0
    - name: Test Project
      uses: threeal/ctest-action@v1.1.0
    - name: Check Test Coverage
      uses: threeal/gcovr-action@v1.1.0
